@startuml
'https://plantuml.com/sequence-diagram

skinparam MaxMessageSize 100
participant ":UserController" as Controller
participant ":UserService" as Service
participant ":UserRepository" as UserRepository
participant ":User" as User

group HTTP PUT /users
    ?-> Controller    : HTTP **PUT** /users/password
    activate Controller

    Controller -> Service: updatePassword(email: String, updatePasswordDTO: UpdatePasswordDTO)
    deactivate Controller
    activate Service

    Service -> UserRepository: updatePassword(userId: Int, hashedPassword: String)
    deactivate Service
    activate UserRepository
    UserRepository -> User:**<<updates>>**
    activate User
    UserRepository <-- User:
    deactivate User
    Service <-- UserRepository: **Int**
    deactivate UserRepository
    Controller <-- Service:

    activate Controller
            ?<- Controller    : HTTP **200**
            deactivate

@enduml